export const PM_ALL_SUBJECTS_SET_QUERY = 'PM_ALL_SUBJECTS_SET_QUERY';

export const PM_ALL_SUBJECTS_GET_SUBJECTS = 'PM_ALL_SUBJECTS_GET_SUBJECTS';
export const PM_ALL_SUBJECTS_GET_SUBJECTS_ERROR = 'PM_ALL_SUBJECTS_GET_SUBJECTS_ERROR';
export const PM_ALL_SUBJECTS_GET_SUBJECTS_SUCCESS = 'PM_ALL_SUBJECTS_GET_SUBJECTS_SUCCESS';

export const PM_ALL_SUBJECTS_DELETE_SUBJECT = 'PM_ALL_SUBJECTS_DELETE_SUBJECT';
export const PM_ALL_SUBJECTS_DELETE_SUBJECT_ERROR = 'PM_ALL_SUBJECTS_DELETE_SUBJECT_ERROR';
export const PM_ALL_SUBJECTS_DELETE_SUBJECT_SUCCESS = 'PM_ALL_SUBJECTS_DELETE_SUBJECT_SUCCESS';

export const PM_ALL_SUBJECTS_SHOW_DELETE_CONFIRM_MODAL_FOR_ID = 'PM_ALL_SUBJECTS_SHOW_DELETE_CONFIRM_MODAL_FOR_ID';
