export const PM_ALL_SUBJECTS_GET_SUBJECTS = 'PM_ALL_SUBJECTS_GET_SUBJECTS';
export const PM_ALL_SUBJECTS_GET_SUBJECTS_ERROR = 'PM_ALL_SUBJECTS_GET_SUBJECTS_ERROR';
export const PM_ALL_SUBJECTS_GET_SUBJECTS_SUCCESS = 'PM_ALL_SUBJECTS_GET_SUBJECTS_SUCCESS';
