apiVersion: v1
items:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: amida-auth-microservice
    name: amida-auth-microservice
  spec:
    failedBuildsHistoryLimit: 5
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: amida-auth-microservice:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      git:
        ref: develop
        uri: https://github.com/amida-tech/amida-auth-microservice.git
      sourceSecret:
        name: amidabot-github
      type: Git
    strategy:
      dockerStrategy:
        env:
        - name: NODE_ENV
          value: development
        - name: JWT_MODE
          value: hmac
        - name: JWT_SECRET
          value: veryverysecret
        - name: PG_DB
          value: auth
        - name: PG_USER
          value: amida
        - name: PG_PASSWD
          value: REDACTED
        - name: PG_PORT
          value: "5432"
        - name: PG_HOST
          value: REDACTED
        - name: MAILER_SERVICE_PROVIDER
          value: Gmail
        from:
          kind: ImageStreamTag
          name: node:6.9.1
      type: Docker
    successfulBuildsHistoryLimit: 5
    triggers:
    - github:
        secret: REDACTED
      type: GitHub
    - generic:
        secret: REDACTED
      type: Generic
    - imageChange: {}
      type: ImageChange
    - type: ConfigChange
  status:
    lastVersion: 0
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: amida-survey-microservice
    name: amida-survey-microservice
  spec:
    failedBuildsHistoryLimit: 5
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: amida-survey-microservice:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      git:
        ref: develop
        uri: https://github.com/amida-tech/amida-survey-microservice
      sourceSecret:
        name: amidabot-github
      type: Git
    strategy:
      dockerStrategy:
        env:
        - name: NODE_ENV
          value: development
        - name: RECREG_DB_NAME
          value: survey
        - name: RECREG_DB_PORT
          value: "5432"
        - name: RECREG_DB_HOST
          value: REDACTED
        - name: RECREG_DB_USER
          value: amida
        - name: RECREG_DB_PASS
          value: REDACTED
        - name: RECREG_DB_DIALECT
          value: postgres
        - name: RECREG_DB_POOL_MAX
          value: "5"
        - name: RECREG_DB_POOL_MIN
          value: "0"
        - name: RECREG_DB_POOL_IDLE
          value: "10000"
        - name: RECREG_LOGGING_LEVEL
          value: emerg
        - name: RECREG_CORS_ORIGIN
          value: '*'
        from:
          kind: ImageStreamTag
          name: nodejs:v6.9.x
      type: Docker
    successfulBuildsHistoryLimit: 5
    triggers:
    - github:
        secret: REDACTED
      type: GitHub
    - generic:
        secret: REDACTED
      type: Generic
    - imageChange: {}
      type: ImageChange
    - type: ConfigChange
  status:
    lastVersion: 0
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: greyscale
    name: greyscale
  spec:
    failedBuildsHistoryLimit: 5
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: greyscale:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      contextDir: backend
      git:
        ref: develop
        uri: https://github.com/amida-tech/greyscale.git
      sourceSecret:
        name: amidabot-github
      type: Git
    strategy:
      dockerStrategy:
        from:
          kind: DockerImage
          name: node:5.10.1
      type: Docker
    successfulBuildsHistoryLimit: 5
    triggers:
    - github:
        secret: REDACTED
      type: GitHub
    - generic:
        secret: REDACTED
      type: Generic
    - type: ConfigChange
  status:
    lastVersion: 0
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: indaba-client
    name: indaba-client
  spec:
    failedBuildsHistoryLimit: 5
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: indaba-client:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      git:
        ref: develop
        uri: https://github.com/amida-tech/indaba-client.git
      sourceSecret:
        name: amidabot-github
      type: Git
    strategy:
      dockerStrategy:
        from:
          kind: DockerImage
          name: node:6.11
      type: Docker
    successfulBuildsHistoryLimit: 5
    triggers:
    - github:
        secret: REDACTED
      type: GitHub
    - generic:
        secret: REDACTED
      type: Generic
    - type: ConfigChange
  status:
    lastVersion: 0
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    generation: 1
    labels:
      app: amida-auth-microservice
    name: amida-auth-microservice
  spec:
    replicas: 1
    selector:
      app: amida-auth-microservice
      deploymentconfig: amida-auth-microservice
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: amida-auth-microservice
          deploymentconfig: amida-auth-microservice
      spec:
        containers:
        - image: 172.30.1.1:5000/indaba-test/amida-auth-microservice@sha256:5067d5714e2261260ca578724eb2d865c654b327b5cc1a42b5533b787d62defc
          imagePullPolicy: Always
          name: amida-auth-microservice
          ports:
          - containerPort: 4000
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - amida-auth-microservice
        from:
          kind: ImageStreamTag
          name: amida-auth-microservice:latest
          namespace: indaba-test
      type: ImageChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    generation: 1
    labels:
      app: amida-survey-microservice
    name: amida-survey-microservice
  spec:
    replicas: 1
    selector:
      app: amida-survey-microservice
      deploymentconfig: amida-survey-microservice
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: amida-survey-microservice
          deploymentconfig: amida-survey-microservice
      spec:
        containers:
        - image: 172.30.1.1:5000/indaba-test/amida-survey-microservice@sha256:91861fa09326672c6b711f7ccda0b74ab331033f0c0291cfa91ebfa26bf0aa59
          imagePullPolicy: Always
          name: amida-survey-microservice
          ports:
          - containerPort: 9005
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - amida-survey-microservice
        from:
          kind: ImageStreamTag
          name: amida-survey-microservice:latest
          namespace: indaba-test
      type: ImageChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    generation: 1
    labels:
      app: greyscale
    name: greyscale
  spec:
    replicas: 1
    selector:
      app: greyscale
      deploymentconfig: greyscale
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: greyscale
          deploymentconfig: greyscale
      spec:
        containers:
        - env:
          - name: INDABA_PG_USERNAME
            value: amida
          - name: INDABA_PG_PASSWORD
            value: REDACTED
          - name: INDABA_PG_HOSTNAME
            value: REDACTED
          - name: AUTH_SALT
            value: supersalty
          - name: JWT_SECRET
            value: veryverysecret
          - name: MEMCACHED_HOST
            value: memcached.indaba-test.svc
          image: 172.30.1.1:5000/indaba-test/greyscale@sha256:45051aa851629fdc4be6c490ae44cebed277f8c5bc6c9cb079c055f89a57e4e2
          imagePullPolicy: Always
          name: greyscale
          ports:
          - containerPort: 3005
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - greyscale
        from:
          kind: ImageStreamTag
          name: greyscale:latest
          namespace: indaba-test
      type: ImageChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    generation: 1
    labels:
      app: indaba-client
    name: indaba-client
  spec:
    replicas: 1
    selector:
      app: indaba-client
      deploymentconfig: indaba-client
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: indaba-client
          deploymentconfig: indaba-client
      spec:
        containers:
        - env:
          - name: API_HTTP_URL
            value: greyscale.indaba-test.svc
          - name: API_HTTPS_URL
            value: greyscale.indaba-test.svc
          image: 172.30.1.1:5000/indaba-test/indaba-client@sha256:fa1f8a36fc80bbb8ce46ae14279a63594d6698b2a6381ac807e4c95401accfe9
          imagePullPolicy: Always
          name: indaba-client
          ports:
          - containerPort: 3000
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - indaba-client
        from:
          kind: ImageStreamTag
          name: indaba-client:latest
          namespace: indaba-test
      type: ImageChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftWebConsole
    creationTimestamp: null
    generation: 1
    labels:
      app: memcached
    name: memcached
  spec:
    replicas: 1
    selector:
      app: memcached
      deploymentconfig: memcached
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftWebConsole
        creationTimestamp: null
        labels:
          app: memcached
          deploymentconfig: memcached
      spec:
        containers:
        - image: memcached@sha256:e91ac736b5309dffb65519bf0e87dbcc67d0691d1936aeaf754ed74fd525e64b
          imagePullPolicy: Always
          name: memcached
          ports:
          - containerPort: 11211
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - memcached
        from:
          kind: ImageStreamTag
          name: memcached:latest
          namespace: indaba-test
      type: ImageChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: amida-auth-microservice
    name: amida-auth-microservice
  spec:
    ports:
    - name: 4000-tcp
      port: 4000
      protocol: TCP
      targetPort: 4000
    selector:
      app: amida-auth-microservice
      deploymentconfig: amida-auth-microservice
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: amida-survey-microservice
    name: amida-survey-microservice
  spec:
    ports:
    - name: 9005-tcp
      port: 9005
      protocol: TCP
      targetPort: 9005
    selector:
      app: amida-survey-microservice
      deploymentconfig: amida-survey-microservice
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: greyscale
    name: greyscale
  spec:
    ports:
    - name: 3005-tcp
      port: 3005
      protocol: TCP
      targetPort: 3005
    selector:
      app: greyscale
      deploymentconfig: greyscale
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: indaba-client
    name: indaba-client
  spec:
    ports:
    - name: 3000-tcp
      port: 3000
      protocol: TCP
      targetPort: 3000
    selector:
      app: indaba-client
      deploymentconfig: indaba-client
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftWebConsole
    creationTimestamp: null
    labels:
      app: memcached
    name: memcached
  spec:
    ports:
    - name: 11211-tcp
      port: 11211
      protocol: TCP
      targetPort: 11211
    selector:
      deploymentconfig: memcached
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata: {}
