// Summary reducer calls.
export const EDIT_SUMMARY_DESCRIPTION = 'EDIT_SUMMARY_DESCRIPTION';
export const SUBNAVIGATE = 'SUBNAVIGATE';
export const ASSIGN_TASK = 'ASSIGN_TASK';
export const ADD_SUBJECT = 'ADD_SUBJECT';
export const DELETE_SUBJECT = 'DELETE_SUBJECT';
export const ADD_STAGE = 'ADD_STAGE';
export const UPDATE_TASK = 'UPDATE_TASK';
export const TOGGLE_FILTER = 'TOGGLE_FILTER';
export const SET_PROJECT_STATUS = 'SET_PROJECT_STATUS';
export const SET_SURVEY_STATUS = 'SET_SURVEY_STATUS';
export const INVITE_USER = 'INVITE_USER';

// Task View
export const UPDATE_TASK_DUE_DATE = 'UPDATE_TASK_DUE_DATE';
export const UPDATE_FLAGGED_QUESTION = 'UPDATE_FLAGGED_QUESTION';
