// Summary reducer calls.
export const GET_WORKFLOW = 'GET_WORKFLOW';
export const UPDATE_WORKFLOW_PROJECT = 'UPDATE_WORKFLOW_PROJECT';
export const UPDATE_WORKFLOW_SURVEY = 'UPDATE_WORKFLOW_SURVEY';
export const EDIT_SUMMARY_DESCRIPTION = 'EDIT_SUMMARY_DESCRIPTION';
export const SUBNAVIGATE = 'SUBNAVIGATE';
export const SHOW_MODAL = 'SHOW_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';
export const ADD_SUBJECT = 'ADD_SUBJECT';
export const TOGGLE_FILTER = 'TOGGLE_FILTER';
