# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  test:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.9
        environment:
        - NODE_ENV: development
        - API_URL: https://backend-route-indaba-staging.b9ad.pro-us-east-1.openshiftapps.com
        - AUTH_API_URL: https://auth-route-indaba-staging.b9ad.pro-us-east-1.openshiftapps.com/api/v0
        - SURVEY_API_URL: https://survey-route-indaba-staging.b9ad.pro-us-east-1.openshiftapps.com/api/1.0
        - MESSAGING_API_URL: https://messaging-route-indaba-staging.b9ad.pro-us-east-1.openshiftapps.com/api
        - SYS_MESSAGE_USER: indaba@example.com
        - SYS_MESSAGE_PASSWORD: password
        - REALM: testorg

    working_directory: ~/repo

    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: yarn
      - run: yarn eslint
      - run: yarn stylelint
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      # - run: yarn test:coverage
    
  publish:
    machine: true
    steps:
      - checkout

      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS

      - run: docker build -t amidatech/indaba-client:$CIRCLE_BRANCH .

      - run: docker push amidatech/indaba-client:$CIRCLE_BRANCH

workflows:
  version: 2
  test-publish:
    jobs:
      - test
      - publish:
          context: indaba
          requires:
            - test
          filters:
            branches:
              only:
                - develop
                - master

