// NewProjectTitle.js modal
export const UPDATE_WIZARD_PROJECT_TITLE = 'UPDATE_WIZARD_PROJECT_TITLE';
export const UPDATE_WIZARD_PROJECT_SUMMARY = 'UPDATE_WIZARD_PROJECT_SUMMARY';

export const REMOVE_USER_FROM_WIZARD = 'REMOVE_USER_FROM_WIZARD';
export const REMOVE_USER_GROUP_FROM_WIZARD = 'REMOVE_USER_GROUP_FROM_WIZARD';
export const ADD_PROJECT_FROM_WIZARD = 'ADD_PROJECT_FROM_WIZARD';
export const GO_TO_STEP = 'GO_TO_STEP';
export const SHOW_COMPLETE_WIZARD = 'SHOW_COMPLETE_WIZARD';
export const ADD_USERS_SET_TAB = 'ADD_USERS_SET_TAB';
export const ADD_USERS_SET_USERS_FILTER = 'ADD_USERS_SET_USERS_FILTER';
export const ADD_USERS_SET_GROUPS_FILTER = 'ADD_USERS_SET_GROUPS_FILTER';

// Modal Shows:
export const SHOW_ADD_STAGE_WIZARD_MODAL = 'SHOW_ADD_STAGE_WIZARD_MODAL';
export const SHOW_ADD_USER_GROUP_WIZARD_MODAL = 'SHOW_ADD_USER_GROUP_WIZARD_MODAL';

export const REPORT_NEW_PROJECT_ERROR = 'REPORT_NEW_PROJECT_ERROR';

// API Calls:
export const POST_PROJECT_WIZARD_SUCCESS = 'POST_PROJECT_WIZARD_SUCCESS';
export const POST_SUBJECTS_WIZARD_SUCCESS = 'POST_SUBJECTS_WIZARD_SUCCESS';
export const DELETE_SUBJECTS_WIZARD_SUCCESS = 'DELETE_SUBJECTS_WIZARD_SUCCESS';
export const POST_WORKFLOW_WIZARD_SUCCESS = 'POST_WORKFLOW_WIZARD_SUCCESS';
export const POST_USER_WIZARD_SUCCESS = 'POST_USER_WIZARD_SUCCESS';
export const POST_GROUP_WIZARD_SUCCESS = 'POST_GROUP_WIZARD_SUCCESS';
export const PUT_STAGE_WIZARD_SUCCESS = 'PUT_STAGE_WIZARD_SUCCESS';
