// NewProjectTitle.js modal
export const UPDATE_WIZARD_PROJECT_TITLE = 'UPDATE_WIZARD_PROJECT_TITLE';
export const UPDATE_WIZARD_PROJECT_SUMMARY = 'UPDATE_WIZARD_PROJECT_SUMMARY';

export const PROJECT_WIZARD_INITIALIZE = 'PROJECT_WIZARD_INITIALIZE';
export const GO_TO_STEP = 'GO_TO_STEP';
export const SHOW_COMPLETE_WIZARD = 'SHOW_COMPLETE_WIZARD';
export const ADD_USERS_SET_TAB = 'ADD_USERS_SET_TAB';
export const ADD_USERS_SET_USERS_FILTER = 'ADD_USERS_SET_USERS_FILTER';
export const ADD_USERS_SET_GROUPS_FILTER = 'ADD_USERS_SET_GROUPS_FILTER';

// Modal Shows:
export const SHOW_ADD_STAGE_WIZARD_MODAL = 'SHOW_ADD_STAGE_WIZARD_MODAL';
export const SHOW_ADD_USER_GROUP_WIZARD_MODAL = 'SHOW_ADD_USER_GROUP_WIZARD_MODAL';
