// NewProjectTitle.js modal
export const UPDATE_WIZARD_PROJECT_TITLE = 'UPDATE_WIZARD_PROJECT_TITLE';
export const UPDATE_WIZARD_PROJECT_SUMMARY = 'UPDATE_WIZARD_PROJECT_SUMMARY';

export const DELETE_SUBJECT_FROM_WIZARD = 'DELETE_SUBJECT_FROM_WIZARD';
export const ADD_USER_TO_WIZARD = 'ADD_USER_TO_WIZARD';
export const REMOVE_USER_FROM_WIZARD = 'REMOVE_USER_FROM_WIZARD';
export const ADD_USER_GROUP_TO_WIZARD = 'ADD_USER_GROUP_TO_WIZARD';
export const REMOVE_USER_GROUP_FROM_WIZARD = 'REMOVE_USER_GROUP_FROM_WIZARD';
export const ADD_STAGE_TO_WIZARD = 'ADD_STAGE_TO_WIZARD';
export const ADD_PROJECT_FROM_WIZARD = 'ADD_PROJECT_FROM_WIZARD';
export const GO_TO_STEP = 'GO_TO_STEP';
export const COMPLETE_WIZARD = 'COMPLETE_WIZARD';
export const ADD_USERS_SET_TAB = 'ADD_USERS_SET_TAB';
export const ADD_USERS_SHOW_SELECT_GROUP_USERS = 'ADD_USERS_SHOW_SELECT_GROUP_USERS';
export const ADD_USERS_SET_USERS_FILTER = 'ADD_USERS_SET_USERS_FILTER';

// API Calls:
export const POST_PROJECT_WIZARD_SUCCESS = 'POST_PROJECT_WIZARD_SUCCESS';
export const POST_PROJECT_WIZARD_FAILURE = 'POST_PROJECT_WIZARD_FAILURE';
export const POST_SUBJECTS_WIZARD_SUCCESS = 'POST_SUBJECTS_WIZARD_SUCCESS';
export const POST_SUBJECTS_WIZARD_FAILURE = 'POST_SUBJECTS_WIZARD_FAILURE';
