export const PM_DASH_SET_SEARCH_QUERY = 'PM_DASH_SET_SEARCH_QUERY';
export const PM_DASH_SET_FILTER = 'PM_DASH_SET_FILTER';

export const PM_DASH_GET_MESSAGES_SUCCESS = 'PM_DASH_GET_MESSAGES_SUCCESS';
export const PM_DASH_GET_MESSAGES_FAILURE = 'PM_DASH_GET_MESSAGES_FAILURE';
