export const FILTERS = {
    ALL_PROJECTS: 'ALL_PROJECTS',
    ACTIVE_PROJECTS: 'ACTIVE_PROJECTS',
    PUBLISHED_SURVEYS: 'PUBLISHED_SURVEYS',
    SURVEYS_IN_DRAFT_MODE: 'SURVEYS_IN_DRAFT_MODE',
    SURVEYS_WITH_FLAGS: 'SURVEYS_WITH_FLAGS',
};
