// UI related.
export const SURVEY_BUILDER_CHANGE_SECTION_VIEW = 'SURVEY_BUILDER_CHANGE_SECTION_VIEW';
export const SURVEY_BUILDER_SHOW_SECTION_DELETE_CONFIRM_MODAL = 'SURVEY_BUILDER_SHOW_SECTION_DELETE_CONFIRM_MODAL';

// Form related.
export const SURVEY_BUILDER_UPDATE_INSTRUCTIONS = 'SURVEY_BUILDER_UPDATE_INSTRUCTIONS';

export const SURVEY_BUILDER_INSERT_SECTION = 'SURVEY_BUILDER_INSERT_SECTION';
export const SURVEY_BUILDER_UPDATE_SECTION = 'SURVEY_BUILDER_UPDATE_SECTION';
export const SURVEY_BUILDER_DELETE_SECTION = 'SURVEY_BUILDER_DELETE_SECTION';

export const SURVEY_BUILDER_INSERT_QUESTION = 'SURVEY_BUILDER_INSERT_QUESTION';
export const SURVEY_BUILDER_UPDATE_QUESTION = 'SURVEY_BUILDER_UPDATE_QUESTION';
export const SURVEY_BUILDER_MOVE_QUESTION = 'SURVEY_BUILDER_MOVE_UP_QUESTION';
export const SURVEY_BUILDER_DELETE_QUESTION = 'SURVEY_BUILDER_DELETE_QUESTION';

export const SURVEY_BUILDER_UPSERT_CHOICE = 'SURVEY_BUILDER_UPSERT_CHOICE';
export const SURVEY_BUILDER_DELETE_CHOICE = 'SURVEY_BUILDER_DELETE_CHOICE';
export const SURVEY_BUILDER_UPSERT_SCALE = 'SURVEY_BUILDER_UPSERT_SCALE';
export const SURVEY_BUILDER_UPSERT_WEIGHT = 'SURVEY_BUILDER_UPSERT_WEIGHT';

export const SURVEY_BUILDER_RESET_META = 'SURVEY_BUILDER_RESET_META';
