// UI related.
export const SURVEY_BUILDER_CHANGE_SECTION = 'SURVEY_BUILDER_CHANGE_SECTION';

// Form related.
export const SURVEY_BUILDER_UPDATE_INSTRUCTIONS = 'SURVEY_BUILDER_UPDATE_INSTRUCTIONS';

export const SURVEY_BUILDER_INSERT_SECTION = 'SURVEY_BUILDER_INSERT_SECTION';
export const SURVEY_BUILDER_UPDATE_SECTION = 'SURVEY_BUILDER_UPDATE_SECTION';

export const SURVEY_BUILDER_INSERT_QUESTION = 'SURVEY_BUILDER_INSERT_QUESTION';
export const SURVEY_BUILDER_UPDATE_QUESTION = 'SURVEY_BUILDER_UPDATE_QUESTION';
export const SURVEY_BUILDER_UPDATE_META = 'SURVEY_BUILDER_UPDATE_META';
export const SURVEY_BUILDER_RESET_META = 'SURVEY_BUILDER_RESET_META';

export const SURVEY_BUILDER_DELETE_QUESTION = 'SURVEY_BUILDER_DELETE_QUESTION';
export const SURVEY_BUILDER_MOVE_QUESTION = 'SURVEY_BUILDER_MOVE_UP_QUESTION';
