export const GET_ALL_PROFILE_DATA = 'GET_ALL_PROFILE_DATA';

export const GET_PROJECT_FOR_PROFILE = 'GET_PROJECT_FOR_PROFILE';
export const GET_PROJECT_FOR_PROFILE_SUCCESS = 'GET_PROJECT_FOR_PROFILE_SUCCESS';
export const GET_PROJECT_FOR_PROFILE_ERROR = 'GET_PROJECT_FOR_PROFILE_ERROR';

export const GET_USER_FOR_PROFILE = 'GET_USER_FOR_PROFILE';
export const GET_USER_FOR_PROFILE_SUCCESS = 'GET_USER_FOR_PROFILE_SUCCESS';
export const GET_USER_FOR_PROFILE_ERROR = 'GET_USER_FOR_PROFILE_ERROR';
