export const GET_ALL_PROFILE_DATA = 'GET_ALL_PROFILE_DATA';

export const GET_TASKS_FOR_PROFILE = 'GET_TASKS_FOR_PROFILE';
export const GET_TASKS_FOR_PROFILE_SUCCESS = 'GET_TASKS_FOR_PROFILE_SUCCESS';
export const GET_TASKS_FOR_PROFILE_FAILURE = 'GET_TASKS_FOR_PROFILE_FAILURE';
