export const GET_USER_FOR_PROFILE = 'GET_USER_FOR_PROFILE';
export const GET_USER_FOR_PROFILE_SUCCESS = 'GET_USER_FOR_PROFILE_SUCCESS';
export const GET_USER_FOR_PROFILE_ERROR = 'GET_USER_FOR_PROFILE_ERROR';
