export const GET_TASKS_FOR_UPDATE_PW = 'GET_TASKS_FOR_UPDATE_PW';
export const GET_TASKS_FOR_UPDATE_PW_SUCCESS = 'GET_TASKS_FOR_UPDATE_PW_SUCCESS';
export const GET_TASKS_FOR_UPDATE_PW_FAILURE = 'GET_TASKS_FOR_UPDATE_PW_FAILURE';
