export const GET_SURVEY_BY_ID         = 'GET_SURVEY_BY_ID_START';
export const GET_SURVEY_BY_ID_SUCCESS = 'GET_SURVEY_BY_ID_SUCCESS';
export const GET_SURVEY_BY_ID_FAILURE = 'GET_SURVEY_BY_ID_FAILURE';

export const GET_SURVEY_ANSWER_BY_ID         = 'GET_SURVEY_ANSWER_BY_ID';
export const GET_SURVEY_ANSWER_BY_ID_SUCCESS = 'GET_SURVEY_ANSWER_BY_ID_SUCCESS';
export const GET_SURVEY_ANSWER_BY_ID_FAILURE = 'GET_SURVEY_ANSWER_BY_ID_FAILURE';

export const GET_SURVEY_CONSENT_BY_ID         = 'GET_SURVEY_CONSENT_BY_ID'
export const GET_SURVEY_CONSENT_BY_ID_SUCCESS = 'GET_SURVEY_CONSENT_BY_ID_SUCCESS'
export const GET_SURVEY_CONSENT_BY_ID_FAILURE = 'GET_SURVEY_CONSENT_BY_ID_FAILURE'
export const SIGN_SURVEY_CONSENT_SUCCESS      = 'SIGN_SURVEY_CONSENT_SUCCESS'
export const SIGN_SURVEY_CONSENT_FAILURE      = 'SIGN_SURVEY_CONSENT_FAILURE'

export const SUBMIT_SURVEY         = 'SUBMIT_SURVEY';
export const SUBMIT_SURVEY_FAILURE = 'SUBMIT_SURVEY_FAILURE';
export const SUBMIT_SURVEY_SUCCESS = 'SUBMIT_SURVEY_SUCCESS';

export const UPDATE_ANSWER    = 'UPDATE_ANSWER';
export const UPDATE_INTEGER_ANSWER = 'UPDATE_INTEGER_ANSWER';
export const UPDATE_FLOAT_ANSWER   = 'UPDATE_FLOAT_ANSWER';
export const UPDATE_DATE_ANSWER    = 'UPDATE_DATE_ANSWER';
export const UPDATE_DAY_ANSWER     = 'UPDATE_DAY_ANSWER';
export const UPDATE_MONTH_ANSWER   = 'UPDATE_MONTH_ANSWER';
export const UPDATE_YEAR_ANSWER    = 'UPDATE_YEAR_ANSWER';
