export const UPDATE_FLAGGED_QUESTION = 'UPDATE_FLAGGED_QUESTION';
export const FORCE_TASK_COMPLETION = 'FORCE_TASK_COMPLETION';

// API calls:
export const GET_DISCUSSION_SUCCESS = 'GET_DISCUSSION_SUCCESS';
export const POST_DISCUSSION_SUCCESS = 'POST_DISCUSSION_SUCCESS';
export const PUT_RESOLVE_SUCCESS = 'PUT_RESOLVE_SUCCESS';
export const REPORT_DISCUSS_ERROR = 'REPORT_DISCUSS_ERROR';
