export const UPDATE_FLAGGED_QUESTION = 'UPDATE_FLAGGED_QUESTION';
export const FORCE_TASK_COMPLETION = 'FORCE_TASK_COMPLETION';

// API calls:
export const GET_DISCUSS_SUCCESS = 'GET_DISCUSS_SUCCESS';
export const PUT_DISCUSS_RESOLVE_SUCCESS = 'PUT_DISCUSS_RESOLVE_SUCCESS';
export const REPORT_DISCUSS_ERROR = 'REPORT_DISCUSS_ERROR';
