export const UPDATE_FLAGGED_QUESTION = 'UPDATE_FLAGGED_QUESTION';

// API calls:
export const GET_DISCUSSIONS_SUCCESS = 'GET_DISCUSSIONS_SUCCESS';
export const POST_DISCUSSION_SUCCESS = 'POST_DISCUSSION_SUCCESS';
export const PUT_DISCUSS_RESOLVE_SUCCESS = 'PUT_DISCUSS_RESOLVE_SUCCESS';
export const REPORT_DISCUSS_ERROR = 'REPORT_DISCUSS_ERROR';
