export const SHOW_CREATE_PROJECT = 'SHOW_CREATE_PROJECT';
export const TOGGLE_CHECK_BACKEND = 'TOGGLE_CHECK_BACKEND';
export const REFRESH_TOKEN_SUCCESS = 'REFRESH_TOKEN_SUCCESS';
export const LOG_OUT = 'LOG_OUT';
