export const EDIT_SUMMARY_DESCRIPTION = 'EDIT_SUMMARY_DESCRIPTION'; // Not yet used.
export const TOGGLE_FILTER = 'TOGGLE_FILTER';
export const SET_PROJECT_STATUS = 'SET_PROJECT_STATUS';
export const DELETE_USER_GROUP = 'DELETE_USER_GROUP';
export const ADD_USER_GROUP = 'ADD_USER_GROUP';
export const UPDATE_USER_GROUP = 'UPDATE_USER_GROUP';
export const ADD_USER = 'ADD_USER';
export const REMOVE_USER = 'REMOVE_USER';
export const SET_PROJECT_NAME = 'SET_PROJECT_NAME';

// Modals:
export const SHOW_ADD_STAGE_MODAL = 'SHOW_ADD_STAGE_MODAL';
export const SHOW_ADD_SUBJECT_MODAL = 'SHOW_ADD_SUBJECT_MODAL';

// Private function types.
export const POST_PROJECT_SUCCESS = 'POST_PROJECT_SUCCESS';
export const GET_PROJECTS_SUCCESS = 'GET_PROJECTS_SUCCESS';
export const GET_PROJECT_BY_ID_SUCCESS = 'GET_PROJECT_BY_ID_SUCCESS';

export const POST_PROJECT_USER_SUCCESS = 'POST_PROJECT_USER_SUCCESS';
export const DELETE_PROJECT_USER_SUCCESS = 'DELETE_PROJECT_USER_SUCCESS';
export const PUT_STAGE_SUCCESS = 'PUT_STAGE_SUCCESS';

export const POST_SUBJECT_SUCCESS = 'POST_SUBJECT_SUCCESS';
export const DELETE_SUBJECT_SUCCESS = 'DELETE_SUBJECT_SUCCESS';

// Errors.
export const REPORT_PROJECT_ERROR = 'REPORT_PROJECT_ERROR';
