// Survey related.
export const GET_SURVEYS_SUCCESS = 'GET_SURVEYS_SUCCESS';
export const POST_SURVEY_SUCCESS = 'POST_SURVEY_SUCCESS';
export const PATCH_SURVEY_SUCCESS = 'PATCH_SURVEY_SUCCESS';
export const GET_SURVEY_BY_ID_SUCCESS = 'GET_SURVEY_BY_ID_SUCCESS';

// Answer related.
export const POST_ASSESSMENT_SUCCESS = 'POST_ASSESSMENT_SUCCESS';
export const GET_ANSWERS_SUCCESS = 'GET_ANSWERS_SUCCESS';
export const POST_ANSWER_SUCCESS = 'POST_ANSWER_SUCCESS';

// UI components
export const SET_SURVEY_SECTION_INDEX = 'SET_SURVEY_SECTION_INDEX';

// Errors.
export const REPORT_SURVEY_ERROR = 'REPORT_SURVEY_ERROR';
