export const SET_SURVEY_STATUS = 'SET_SURVEY_STATUS';
export const SET_SURVEY_NAME = 'SET_SURVEY_NAME';
export const SET_SURVEY_SECTION_INDEX = 'SET_SURVEY_SECTION_INDEX';

// Private function types.
export const POST_SURVEY_SUCCESS = 'POST_SURVEY_SUCCESS';
export const PATCH_SURVEY_SUCCESS = 'PATCH_SURVEY_SUCCESS';
export const GET_SURVEYS_SUCCESS = 'GET_SURVEYS_SUCCESS';
export const GET_SURVEY_BY_ID_SUCCESS = 'GET_SURVEY_BY_ID_SUCCESS';

// Errors.
export const REPORT_SURVEY_ERROR = 'REPORT_SURVEY_ERROR';
