export const SET_SURVEY_STATUS = 'SET_SURVEY_STATUS';
export const SET_SURVEY_NAME = 'SET_SURVEY_NAME';

// Private function types.
export const POST_SURVEY_SUCCESS = 'POST_SURVEY_SUCCESS';
export const GET_SURVEYS_SUCCESS = 'GET_SURVEYS_SUCCESS';
export const GET_SURVEY_BY_ID_SUCCESS = 'GET_SURVEY_BY_ID_SUCCESS';

export const ADD_SURVEY_QUESTION = 'ADD_SURVEY_QUESTION';

// Errors.
export const REPORT_SURVEY_ERROR = 'REPORT_SURVEY_ERROR';
