export const UPDATE_TASK_DUE_DATE = 'UPDATE_TASK_DUE_DATE';

// API Calls:
export const GET_TASKS_BY_PRODUCT_SUCCESS = 'GET_TASKS_BY_PRODUCT_SUCCESS';
export const GET_TASK_BY_ID_SUCCESS = 'GET_TASK_BY_ID_SUCCESS';
export const GET_TASKS_BY_USER_SUCCESS = 'GET_TASKS_BY_USER_SUCCESS';
export const POST_TASK_SUCCESS = 'POST_TASK_SUCCESS';
export const PUT_TASK_SUCCESS = 'PUT_TASK_SUCCESS';
export const PUT_TASK_SUCCESS = 'DELETE_TASK_SUCCESS';

// UI:
export const REPORT_TASKS_ERROR = 'REPORT_TASKS_ERROR';
