export const ADD_NEW_USER = 'ADD_NEW_USER';
export const POST_NEW_USER_SUCCESS = 'POST_NEW_USER_SUCCESS';
export const NOTIFY_USER = 'NOTIFY_USER';

// API calls.
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const PUT_PROFILE_SUCCESS = 'PUT_PROFILE_SUCCESS';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const REPORT_USER_ERROR = 'REPORT_USER_ERROR';

export const UPDATE_PROFILE_BY_ID = 'UPDATE_PROFILE_BY_ID';
export const UPDATE_PROFILE_BY_ID_SUCCESS = 'UPDATE_PROFILE_BY_ID_SUCCESS';
export const UPDATE_PROFILE_BY_ID_FAILURE = 'UPDATE_PROFILE_BY_ID_FAILURE';
