export const SET_USER_FIRST_NAME = 'SET_USER_FIRST_NAME';
export const SET_USER_LAST_NAME = 'SET_USER_LAST_NAME';
export const SET_USER_EMAIL = 'SET_USER_EMAIL';
export const SET_USER_TITLE = 'SET_USER_TITLE';
