export const USER_DASH_SET_SEARCH_QUERY = 'USER_DASH_SET_SEARCH_QUERY';
export const USER_DASH_SET_FILTER = 'USER_DASH_SET_FILTER';

export const USER_DASH_GET_MESSAGES_SUCCESS = 'USER_DASH_GET_MESSAGES_SUCCESS';
export const USER_DASH_GET_MESSAGES_FAILURE = 'USER_DASH_GET_MESSAGES_FAILURE';
