export const FILTERS = {
    ALL_TASKS: 'ALL_TASKS',
    NEW_TASKS: 'NEW_TASKS',
    LATE_TASKS: 'LATE_TASKS',
    DUE_TODAY: 'DUE_TODAY',
    FLAGS: 'FLAGS',
    DUE_TOMORROW: 'DUE_TOMORROW',
    DUE_THIS_WEEK: 'DUE_THIS_WEEK',
    COMPLETED: 'COMPLETED',
};
