export const FILTERS = {
    ALL_PROJECTS: 'ALL_PROJECTS',
    NEW_TASKS: 'NEW_TASKS',
    LATE_TASK: 'LATE_TASKS',
    DUE_TODAY: 'DUE_TODAY',
    FLAGS: 'FLAGS',
    DUE_TOMORROW: 'DUE_TOMORROW',
    DUE_THIS_WEEK: 'DUE_THIS_WEEK',
};
