export const PM_ALL_USERS_SHOW_PROFILE = 'PM_ALL_USERS_SHOW_PROFILE';
export const PM_ALL_USERS_SET_LIST_QUERY = 'PM_ALL_USERS_SET_LIST_QUERY';
export const PM_ALL_USERS_SHOW_DELETE_CONFIRM_MODAL = 'PM_ALL_USERS_SHOW_DELETE_CONFIRM_MODAL';
export const PM_ALL_USERS_HIDE_DELETE_CONFIRM_MODAL = 'PM_ALL_USERS_HIDE_DELETE_CONFIRM_MODAL';
