// Survey Form:
export const UPDATE_FORM_SURVEY_ID = 'UPDATE_FORM_SURVEY_ID';
export const UPSERT_ANSWER = 'UPSERT_ANSWER';

export const STORE_FLAGGED_ISSUES = 'STORE_FLAGGED_ISSUES';
export const UPDATE_QUESTION_DISPLAY = 'UPDATE_QUESTION_DISPLAY';
export const SET_ACTIVE_FLAG = 'SET_ACTIVE_FLAG';
export const SET_SIGNATURE_ID = 'SET_SIGNATURE_ID';
export const UPDATE_MARK_RESOLVED = 'UPDATE_MARK_RESOLVED';
export const UPDATE_NOTIFY_USER = 'UPDATE_NOTIFY_USER';
