// Survey Form:
export const UPDATE_FORM_SURVEY_ID = 'UPDATE_FORM_SURVEY_ID';
export const UPSERT_ANSWER = 'UPSERT_ANSWER';
export const HOLD_ANSWER = 'HOLD_ANSWER';

export const UPDATE_MARK_RESOLVED = 'UPDATE_MARK_RESOLVED';

// UI Calls:
export const SET_ACTIVE_FLAG = 'SET_ACTIVE_FLAG';
export const UPDATE_QUESTION_DISPLAY = 'UPDATE_QUESTION_DISPLAY';

// API calls:
export const GET_DISCUSSIONS_SUCCESS = 'GET_DISCUSSIONS_SUCCESS';
export const POST_DISCUSSION_SUCCESS = 'POST_DISCUSSION_SUCCESS';
export const PUT_DISCUSS_RESOLVE_SUCCESS = 'PUT_DISCUSS_RESOLVE_SUCCESS';
export const REPORT_DISCUSS_ERROR = 'REPORT_DISCUSS_ERROR';
