export const LOGIN = 'LOGIN';
export const LOGIN_LOADING = 'LOGIN_LOADING';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const CLEAR_LOGIN_FORM = 'CLEAR_LOGIN_FORM';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const GET_CURRENT_USER_FAILURE = 'GET_CURRENT_USER_FAILURE';
export const GET_USERS_FAILURE = 'GET_USERS_FAILURE';
