export const UPDATE_LOGIN_USERNAME = 'UPDATE_LOGIN_USERNAME';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_UI_MESSAGE = 'LOGIN_UI_MESSAGE';
export const LOGIN_SHOW_FORGOT_PASSWORD = 'LOGIN_SHOW_FORGOT_PASSWORD';
export const LOGIN_CLEAR_FORM = 'LOGIN_CLEAR_FORM';
export const REQUEST_RESET_TOKEN_SUCCESS = 'REQUEST_RESET_TOKEN_SUCCESS';
